service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-2
  profile: Local

package:
  exclude:
    - .git/**
    - .vscode/**
    - .cirlceci/**
    - files/**

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          cors: true
          path: '/{proxy+}'
          method: any
