version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - node/install
      - build:
          requires:
            - node/install
      - start:
          requires:
            - build

jobs:
  node/install:
    executor: node/default
    steps:
      - checkout

  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Build
          command: yarn build

  start:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Start prod
          command: yarn start:prod
