version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:18

orbs:
  node: circleci/node@4.7

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - node/install
      - build:
          requires:
            - node/install
      - start:
          requires:
            - build

jobs:
  node/install:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - node/install-packages # Use the node orb's pre-built command to install dependencies

  build:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - run:
          name: Build
          command: yarn build

  start:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - run:
          name: Start prod
          command: yarn start:prod
