version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:20.5.0

orbs:
  node: circleci/node@4.7

workflows:
  version: 2
  DeployMain:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - main

jobs:
  build_and_deploy:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Start
          command: yarn start:prod
