version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:18

orbs:
  node: circleci/node@4.7

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - node/install
      - build:
          requires:
            - node/install
      - start:
          requires:
            - build

jobs:
  install:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - run:
          name: Install
          command: yarn
  build:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - run:
          name: Build
          command: yarn build

  start:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - run:
          name: Start prod
          command: yarn start:prod
