version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:20.5.0

orbs:
  node: circleci/node@4.7

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - start:
          requires:
            - build

jobs:
  install:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - run:
          name: Install
          command: yarn
  build:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - run:
          name: Build
          command: yarn build

  start:
    executor: default # Use the defined executor for this job
    steps:
      - checkout
      - run:
          name: Start prod
          command: yarn start:prod
