export enum EnvVar {
  JWT_SECRET = 'JWT_SECRET',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER_NAME = 'DB_USER_NAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  MAIL_USER_NAME = 'MAIL_USER_NAME',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
  FRONT_END_URL = 'FRONT_END_URL',
  OAUTH_CLIENT_ID = 'OAUTH_CLIENT_ID',
  OAUTH_SECRET = 'OAUTH_SECRET',
  OAUTH_REFRESH_TOKEN = 'OAUTH_REFRESH_TOKEN',
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  CLIENT_URL = 'CLIENT_URL',
}

export enum TRANSACTION_STATUS {
  PENDING = 'pending',
  SUCCESS = 'success',
  FAILED = 'failed',
}