export enum EnvVar {
  JWT_SECRET = 'JWT_SECRET',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER_NAME = 'DB_USER_NAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  MAIL_USER_NAME = 'MAIL_USER_NAME',
  MAIL_PASSWORD = 'MAIL_PASSWORD',
}
